stages:
  - build

nexus:
  stage: build
  image: data61/magda-builder-docker:latest
  services:
    - docker:dind
  rules:
    - changes:
        - src/**
        - .gitlab-ci.yml
      when: on_success
  script:
    - cd src/
    - docker login -u "$NEXUS_USER" -p "$NEXUS_PASS" "$NEXUS_REGISTRY"
    - docker context create builder-context
    - docker buildx create --name builderx --driver docker-container --use builder-context
    - |
      SHORT_SHA=$(echo "$CI_COMMIT_SHA" | cut -c1-7)
      docker buildx build \
        --platform=linux/arm64,linux/amd64 \
        --push \
        -f Dockerfile \
        -t "$NEXUS_REGISTRY/$CI_PROJECT_PATH:sha-$SHORT_SHA" \
        .

docker-hub:
  stage: build
  image: data61/magda-builder-docker:latest
  services:
    - docker:dind
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
  script:
    - cd src/
    - docker login -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
    - docker context create builder-context
    - docker buildx create --name builderx --driver docker-container --use builder-context
    - docker buildx build \
        --platform=linux/arm64,linux/amd64 \
        --push \
        -f Dockerfile \
        -t "$CI_PROJECT_PATH:latest" \
        -t "$CI_PROJECT_PATH:$CI_COMMIT_TAG" \
        .